[toolchain]
package_manager = "yarn"

[test]
startup_wait = 20000

[features]
resolution = true
skip-lint = false

[programs.localnet]
lsd = "HTzFDPRGYAjwtYqx4ah8VRUCqedbC9dbs66a1k8tyDNh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
